<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>2.0.1</Version>
    <VersionSuffix>$(VersionSuffix)</VersionSuffix>
    <Version Condition=" '$(VersionSuffix)' != '' ">$(Version)-$(VersionSuffix)</Version>
    <IsPackable>true</IsPackable>
    <TargetFrameworks>net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <IsTrimmable>true</IsTrimmable>
    <Authors>Sergey Pismennyi; Svetlana Pismennaya</Authors>
    <Company>MONQ Digital lab</Company>
    <Title>Monq.Core.Redis</Title>
    <PackageId>Monq.Core.Redis</PackageId>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageTags>library dependency-injection redis di netcore</PackageTags>
    <PackageProjectUrl>https://github.com/MONQDL/Monq.Core.Redis</PackageProjectUrl>
    <RepositoryUrl>https://github.com/MONQDL/Monq.Core.Redis</RepositoryUrl>
    <Description>The Monq.Core.Redis library introduces easy-to-configure methods to connect Redis.</Description>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
    <PackageReference Include="StackExchange.Redis" Version="2.8.58" />
  </ItemGroup>

  <ItemGroup Condition="
    '$(TargetFramework)' == 'net8.0' Or
    '$(TargetFramework)' == 'net9.0' Or
    '$(TargetFramework)' == 'net10.0'">
    <PackageReference Include="StackExchange.Redis" Version="2.10.1" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
